
import com.itextpdf.text.BadElementException;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.Rectangle;
import java.awt.Toolkit;
import java.io.IOException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.logging.Level;
import java.util.logging.Logger;
import javafx.util.converter.LocalDateTimeStringConverter;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author petot
 */
public class Principal extends javax.swing.JFrame {

    ConectorProfundo cP=new ConectorProfundo();
    ConectorBD cbd=new ConectorBD();
  
    public Principal() {
        initComponents();
        this.setSize((int)this.getAncho(),(int)this.getAlto());
    }
    public double getAncho(){
        Toolkit t = Toolkit.getDefaultToolkit();
        Dimension detectorDeDimensiones = Toolkit.getDefaultToolkit().getScreenSize();
        return detectorDeDimensiones.getWidth();

    }
      public double getAlto(){
        Toolkit t = Toolkit.getDefaultToolkit();
        Dimension detectorDeDimensiones = Toolkit.getDefaultToolkit().getScreenSize();
        return detectorDeDimensiones.getHeight();

    }
    public void actualizarListaProveedores(){
            List<ResultadoSentencia> proveedores=cbd.getNombreProveedor();
            proveedores.stream()
                      .forEach(e -> cmbProveedoresz.addItem(e.getNombre()));
    }
    public LocalDate getDesde(){
        String desdeStr=txtAñoDe.getText()+"/"+txtMesDe.getText()+"/"+txtDiaDe.getText();
        return LocalDate.parse(desdeStr,DateTimeFormatter.ofPattern("yyyy/MM/dd"));
    }
    public LocalDate getHasta(){
        String hastaStr=txtAñoHa.getText()+"/"+txtMesHa.getText()+"/"+txtDiaHa.getText();
        return LocalDate.parse(hastaStr,DateTimeFormatter.ofPattern("yyyy/MM/dd"));
    }
    public String formarTextoSalida(List<ResultadoSentencia> resultado){
        String salidaPantalla="";
        String añadirEspacio="";
        double total=0;
        for(int i=0;i<resultado.size();i++){
             
            añadirEspacio=resultado.get(i).getNombre();
            while(añadirEspacio.length()<25){
                añadirEspacio+="  ";
            }
            salidaPantalla+="-"+añadirEspacio+resultado.get(i).getCantidad()+"        "
                    +"        "+resultado.get(i).getFecha()+"\n";
        }
        return salidaPantalla;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel7 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnRegistradora = new javax.swing.JButton();
        jPanelRegistrar = new javax.swing.JPanel();
        cmbProveedoresz = new javax.swing.JComboBox<>();
        cmbTipo = new javax.swing.JComboBox<>();
        txtCantidad = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        btnAñadir = new javax.swing.JButton();
        btnBorrar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtAreaNombre = new javax.swing.JTextArea();
        jLabel12 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        txtNombrePrveedor = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        btnAñadirProveedor = new javax.swing.JButton();
        btnBorrarProveedor = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtAñoDe = new javax.swing.JTextField();
        txtMesDe = new javax.swing.JTextField();
        txtDiaDe = new javax.swing.JTextField();
        txtAñoHa = new javax.swing.JTextField();
        txtMesHa = new javax.swing.JTextField();
        txtDiaHa = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        btnMostrarPorProveedor = new javax.swing.JButton();
        btnDetalles = new javax.swing.JButton();
        btnMostrarVentas = new javax.swing.JButton();
        btnVentaDia = new javax.swing.JButton();
        btnBalance = new javax.swing.JButton();
        btnDeudaProveedor = new javax.swing.JButton();
        btnMostrarGastosRango = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        btnRecetas = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        lblFondo = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAutoRequestFocus(false);
        setBackground(new java.awt.Color(124, 123, 123));
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(592, 0, 299, -1));

        btnRegistradora.setBackground(new java.awt.Color(153, 153, 255));
        btnRegistradora.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnRegistradora.setForeground(new java.awt.Color(255, 255, 255));
        btnRegistradora.setText("REGISTRADORA");
        btnRegistradora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistradoraActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegistradora, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 270, 70));

        jPanelRegistrar.setBackground(new java.awt.Color(102, 102, 255));
        jPanelRegistrar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 51)));

        cmbProveedoresz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbProveedoreszActionPerformed(evt);
            }
        });

        txtCantidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCantidadActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setText("Selecciona");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Tipo:");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setText("Importe");

        btnAñadir.setBackground(new java.awt.Color(0, 0, 51));
        btnAñadir.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnAñadir.setForeground(new java.awt.Color(255, 255, 255));
        btnAñadir.setText("Añadir");
        btnAñadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAñadirActionPerformed(evt);
            }
        });

        btnBorrar.setBackground(new java.awt.Color(0, 0, 51));
        btnBorrar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnBorrar.setForeground(new java.awt.Color(255, 255, 255));
        btnBorrar.setText("Borrar");
        btnBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarActionPerformed(evt);
            }
        });

        jLabel7.setBackground(new java.awt.Color(0, 0, 51));
        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("REGISTRAR FACTURAS O ALBARANES");

        javax.swing.GroupLayout jPanelRegistrarLayout = new javax.swing.GroupLayout(jPanelRegistrar);
        jPanelRegistrar.setLayout(jPanelRegistrarLayout);
        jPanelRegistrarLayout.setHorizontalGroup(
            jPanelRegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRegistrarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelRegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 288, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelRegistrarLayout.createSequentialGroup()
                        .addGroup(jPanelRegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanelRegistrarLayout.createSequentialGroup()
                                .addGroup(jPanelRegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanelRegistrarLayout.createSequentialGroup()
                                        .addGap(33, 33, 33)
                                        .addComponent(jLabel11))
                                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanelRegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(cmbProveedoresz, 0, 122, Short.MAX_VALUE)
                                    .addComponent(cmbTipo, 0, 122, Short.MAX_VALUE)
                                    .addComponent(txtCantidad)))
                            .addGroup(jPanelRegistrarLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(jPanelRegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btnBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnAñadir, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(22, 22, 22))))
        );
        jPanelRegistrarLayout.setVerticalGroup(
            jPanelRegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRegistrarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanelRegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(cmbProveedoresz, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelRegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(29, 29, 29)
                .addGroup(jPanelRegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addGap(36, 36, 36)
                .addComponent(btnBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnAñadir, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        getContentPane().add(jPanelRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 300, 320));

        jPanel5.setBackground(new java.awt.Color(102, 102, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 51)));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtAreaNombre.setColumns(20);
        txtAreaNombre.setFont(new java.awt.Font("Myanmar Text", 1, 18)); // NOI18N
        txtAreaNombre.setRows(5);
        jScrollPane2.setViewportView(txtAreaNombre);

        jPanel5.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 32, 490, 560));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("NOMBRE");
        jPanel5.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("CANTIDAD");
        jPanel5.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 10, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("FECHA");
        jPanel5.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 10, -1, -1));

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 140, 520, 600));

        jPanel6.setBackground(new java.awt.Color(102, 102, 255));
        jPanel6.setForeground(new java.awt.Color(255, 255, 255));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel13.setText("Nombre:");

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("REGISTRAR PROVEEDOR");

        btnAñadirProveedor.setBackground(new java.awt.Color(0, 0, 51));
        btnAñadirProveedor.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnAñadirProveedor.setForeground(new java.awt.Color(255, 255, 255));
        btnAñadirProveedor.setText("Añadir");
        btnAñadirProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAñadirProveedorActionPerformed(evt);
            }
        });

        btnBorrarProveedor.setBackground(new java.awt.Color(0, 0, 51));
        btnBorrarProveedor.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnBorrarProveedor.setForeground(new java.awt.Color(255, 255, 255));
        btnBorrarProveedor.setText("Borrar");
        btnBorrarProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarProveedorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(53, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnAñadirProveedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtNombrePrveedor)
                            .addComponent(btnBorrarProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25))))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel14)
                .addGap(35, 35, 35)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(txtNombrePrveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(btnAñadirProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnBorrarProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 510, 300, 230));

        jPanel3.setBackground(new java.awt.Color(102, 102, 255));
        jPanel3.setForeground(new java.awt.Color(255, 255, 255));
        jPanel3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Año             Mes                   Dia");

        jLabel3.setText("Desde:");

        jLabel4.setText("Hasta:");

        txtAñoDe.setText("2001");
        txtAñoDe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAñoDeActionPerformed(evt);
            }
        });

        txtMesDe.setText("01");
        txtMesDe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMesDeActionPerformed(evt);
            }
        });

        txtDiaDe.setText("01");

        txtAñoHa.setText("2023");
        txtAñoHa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAñoHaActionPerformed(evt);
            }
        });

        txtMesHa.setText("01");
        txtMesHa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMesHaActionPerformed(evt);
            }
        });

        txtDiaHa.setText("01");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtAñoHa, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                            .addComponent(txtAñoDe))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtMesDe, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE)
                            .addComponent(txtMesHa))
                        .addGap(31, 31, 31)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtDiaDe, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDiaHa, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 263, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtAñoDe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMesDe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDiaDe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAñoHa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMesHa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDiaHa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 630, 360, 110));

        jPanel1.setBackground(new java.awt.Color(102, 102, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 51)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnMostrarPorProveedor.setBackground(new java.awt.Color(0, 0, 51));
        btnMostrarPorProveedor.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnMostrarPorProveedor.setForeground(new java.awt.Color(255, 255, 255));
        btnMostrarPorProveedor.setText("PROVEEDOR");
        btnMostrarPorProveedor.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                btnMostrarPorProveedorStateChanged(evt);
            }
        });
        btnMostrarPorProveedor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnMostrarPorProveedorMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnMostrarPorProveedorMouseExited(evt);
            }
        });
        btnMostrarPorProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarPorProveedorActionPerformed(evt);
            }
        });
        jPanel1.add(btnMostrarPorProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 298, 49));

        btnDetalles.setBackground(new java.awt.Color(0, 0, 51));
        btnDetalles.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnDetalles.setForeground(new java.awt.Color(255, 255, 255));
        btnDetalles.setText("DETALLES");
        btnDetalles.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnDetallesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnDetallesMouseExited(evt);
            }
        });
        btnDetalles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDetallesActionPerformed(evt);
            }
        });
        jPanel1.add(btnDetalles, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 298, 52));

        btnMostrarVentas.setBackground(new java.awt.Color(0, 0, 51));
        btnMostrarVentas.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnMostrarVentas.setForeground(new java.awt.Color(255, 255, 255));
        btnMostrarVentas.setText("VENTAS");
        btnMostrarVentas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnMostrarVentasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnMostrarVentasMouseExited(evt);
            }
        });
        btnMostrarVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarVentasActionPerformed(evt);
            }
        });
        jPanel1.add(btnMostrarVentas, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 298, 54));

        btnVentaDia.setBackground(new java.awt.Color(0, 0, 51));
        btnVentaDia.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnVentaDia.setForeground(new java.awt.Color(255, 255, 255));
        btnVentaDia.setText("CAJA DIA");
        btnVentaDia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnVentaDiaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnVentaDiaMouseExited(evt);
            }
        });
        btnVentaDia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVentaDiaActionPerformed(evt);
            }
        });
        jPanel1.add(btnVentaDia, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 298, 51));

        btnBalance.setBackground(new java.awt.Color(0, 0, 51));
        btnBalance.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnBalance.setForeground(new java.awt.Color(255, 255, 255));
        btnBalance.setText("BALANCE");
        btnBalance.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBalanceMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnBalanceMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnBalanceMouseExited(evt);
            }
        });
        btnBalance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBalanceActionPerformed(evt);
            }
        });
        jPanel1.add(btnBalance, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, 298, 54));

        btnDeudaProveedor.setBackground(new java.awt.Color(0, 0, 51));
        btnDeudaProveedor.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnDeudaProveedor.setForeground(new java.awt.Color(255, 255, 255));
        btnDeudaProveedor.setText("DEUDA");
        btnDeudaProveedor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnDeudaProveedorMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnDeudaProveedorMouseExited(evt);
            }
        });
        btnDeudaProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeudaProveedorActionPerformed(evt);
            }
        });
        jPanel1.add(btnDeudaProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, 298, 52));

        btnMostrarGastosRango.setBackground(new java.awt.Color(0, 0, 51));
        btnMostrarGastosRango.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnMostrarGastosRango.setForeground(new java.awt.Color(255, 255, 255));
        btnMostrarGastosRango.setText("FACTURAS");
        btnMostrarGastosRango.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnMostrarGastosRangoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnMostrarGastosRangoMouseExited(evt);
            }
        });
        btnMostrarGastosRango.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarGastosRangoActionPerformed(evt);
            }
        });
        jPanel1.add(btnMostrarGastosRango, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 400, 298, 51));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 140, 360, 480));

        btnSalir.setBackground(new java.awt.Color(153, 153, 255));
        btnSalir.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnSalir.setForeground(new java.awt.Color(255, 255, 255));
        btnSalir.setText("SALIR");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 30, 240, 70));

        btnRecetas.setBackground(new java.awt.Color(153, 153, 255));
        btnRecetas.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnRecetas.setForeground(new java.awt.Color(255, 255, 255));
        btnRecetas.setText("RECETA");
        btnRecetas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRecetasActionPerformed(evt);
            }
        });
        getContentPane().add(btnRecetas, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 30, 270, 70));

        jButton1.setBackground(new java.awt.Color(153, 153, 255));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("GRAFICA");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 30, 300, 70));

        lblFondo.setBackground(new java.awt.Color(0, 0, 51));
        lblFondo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblFondo.setForeground(new java.awt.Color(255, 255, 255));
        lblFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondo.jpg"))); // NOI18N
        lblFondo.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(204, 204, 255), null));
        getContentPane().add(lblFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1340, 790));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarActionPerformed
       
        Integer valor=Integer.valueOf(txtCantidad.getText());
        cbd.borrarGasto(valor, cmbProveedoresz.getSelectedItem().toString().toUpperCase(),this.getDesde(),cmbTipo.getSelectedItem().toString());
    }//GEN-LAST:event_btnBorrarActionPerformed

    
    private void cmbProveedoreszActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbProveedoreszActionPerformed
        
    }//GEN-LAST:event_cmbProveedoreszActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        
            this.actualizarListaProveedores();
              
            cmbTipo.addItem("facturas");
            cmbTipo.addItem("albaran");
            
            String añadirCeroFechaMes=LocalDate.now().getMonthValue()<10 ? "0"+""+LocalDate.now().getMonthValue():LocalDate.now().getMonthValue()+"";
            String añadirCeroFechaDia=LocalDate.now().getDayOfMonth()<10 ? "0"+""+LocalDate.now().getDayOfMonth():LocalDate.now().getDayOfMonth()+"";
            txtAñoHa.setText(LocalDate.now().getYear()+"");
            txtMesHa.setText(añadirCeroFechaMes);
            txtDiaHa.setText(añadirCeroFechaDia);
            txtAñoDe.setText(LocalDate.now().getYear()+"");
            txtMesDe.setText(LocalDate.now().getMonthValue()<10 ? "0"+""+(LocalDate.now().getMonthValue()-1):LocalDate.now().getMonthValue()+"");
            txtDiaDe.setText(añadirCeroFechaDia);
            
    }//GEN-LAST:event_formWindowOpened

    private void btnAñadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAñadirActionPerformed
       if(txtCantidad.getText().matches("[+-]?\\d*(\\.\\d+)?")&&!txtCantidad.getText().equals("")){
           
            Double valor=Double.valueOf(txtCantidad.getText());
            String nombreSeleccionado=cmbProveedoresz.getSelectedItem().toString().toUpperCase(); 
            cbd.comprobarAlbaranes(valor, nombreSeleccionado);
            cbd.registrarGasto(valor, LocalDate.now(), cmbProveedoresz.getSelectedItem().toString().toUpperCase(),cmbTipo.getSelectedItem().toString());
           
            JOptionPane.showMessageDialog(rootPane, "Registrado");        
            
       }else{
           JOptionPane.showMessageDialog(rootPane, "NO SON NUMEROS");
       }
    }//GEN-LAST:event_btnAñadirActionPerformed

    private void btnRegistradoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistradoraActionPerformed
        
        new CajaRegistradora(this,true).setVisible(true);
        
    }//GEN-LAST:event_btnRegistradoraActionPerformed

    private void txtCantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCantidadActionPerformed

    }//GEN-LAST:event_txtCantidadActionPerformed

    private void txtMesHaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMesHaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMesHaActionPerformed

    private void txtAñoHaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAñoHaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAñoHaActionPerformed

    private void txtMesDeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMesDeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMesDeActionPerformed

    private void txtAñoDeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAñoDeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAñoDeActionPerformed

    private void btnBorrarProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarProveedorActionPerformed
        ConectorBD cb =new ConectorBD();
        cb.borrarProveedor(txtNombrePrveedor.getText().toUpperCase());
    }//GEN-LAST:event_btnBorrarProveedorActionPerformed

    private void btnAñadirProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAñadirProveedorActionPerformed
        ConectorBD cb =new ConectorBD();
        cb.añadirProveedor(txtNombrePrveedor.getText().toUpperCase());
        cmbProveedoresz.removeAllItems();
        this.actualizarListaProveedores();
        JOptionPane.showMessageDialog(rootPane, "Registrado");        

    }//GEN-LAST:event_btnAñadirProveedorActionPerformed

    private void btnVentaDiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVentaDiaActionPerformed

        List<ResultadoSentencia> ventas=new ArrayList<>();

        ventas=cbd.getGastos(LocalDate.now(),LocalDate.now(),"caja");
        
        Double resultadoFormadoVentas=cbd.getGastos(LocalDate.now(),LocalDate.now(),"caja").stream()
        .mapToDouble(e -> Double.valueOf(e.getCantidad()))
        .sum();
        
         txtAreaNombre.setText(this.formarTextoSalida(ventas)+"\n   TOTAL= "+resultadoFormadoVentas);
    }//GEN-LAST:event_btnVentaDiaActionPerformed

    private void btnDetallesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDetallesActionPerformed
        ConectorBD cb=new ConectorBD();
        List<String> listaPlatos=cb.getListaPlatos();

        int[] detallesVentas=cb.getDetallesVenta(this.getDesde(),this.getHasta());
        String resultadoPantalla="";
        for(int i=0;i<detallesVentas.length;i++){
            resultadoPantalla+=listaPlatos.get(i)+"  ------->  "+detallesVentas[i]+" und\n\n";
          
        }
        txtAreaNombre.setText(resultadoPantalla);
    }//GEN-LAST:event_btnDetallesActionPerformed

    private void btnMostrarGastosRangoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarGastosRangoActionPerformed

        ConectorBD cbd=new ConectorBD();

        List<ResultadoSentencia> gastos=cbd.getGastos(this.getDesde(),this.getHasta(),"facturas");     
        txtAreaNombre.setText(this.formarTextoSalida(gastos));

    }//GEN-LAST:event_btnMostrarGastosRangoActionPerformed

    private void btnBalanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBalanceActionPerformed

        Double resultadoFormadoVentas=cbd.getGastos(this.getDesde(),this.getHasta(),"caja").stream()
        .mapToDouble(e -> Double.valueOf(e.getCantidad()))
        .sum();

        Double resultadoTodasFacturas=cbd.getGastos(this.getDesde(),this.getHasta(),"facturas").stream()
        .mapToDouble(e -> Double.valueOf(e.getCantidad()))
        .sum();
        Double total=resultadoFormadoVentas-resultadoTodasFacturas;
        txtAreaNombre.setText("Ventas desde: "+this.getDesde()+" Hasta: "+this.getHasta()+"\n --> "+resultadoFormadoVentas+"\n\n"
                + "Facturas desde: "+this.getDesde()+" Hasta: "+this.getHasta()+"\n --> "+resultadoTodasFacturas+"\n"
                        + "\nTOTAL BALANCE: "+total);

    }//GEN-LAST:event_btnBalanceActionPerformed

    private void btnDeudaProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeudaProveedorActionPerformed

        ConectorBD cbd=new ConectorBD();

        List<ResultadoSentencia> gastos=cbd.getGastos(LocalDate.parse("01/01/2000"
                ,DateTimeFormatter.ofPattern( "dd/MM/yyyy"))
                ,LocalDate.now(),"albaran");      
        txtAreaNombre.setText(this.formarTextoSalida(gastos));
      
    }//GEN-LAST:event_btnDeudaProveedorActionPerformed

    private void btnMostrarVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarVentasActionPerformed
        List<ResultadoSentencia> ventas=cbd.getGastos(this.getDesde(),this.getHasta(),"caja");
        String resultadoPantalla=this.formarTextoSalida(ventas);
        Double resultadoFormadoVentas=ventas.stream()
            .mapToDouble(e -> Double.valueOf(e.getCantidad()))
            .sum();
        txtAreaNombre.setText(resultadoPantalla+"\n\nTOTAL: "+resultadoFormadoVentas);

    }//GEN-LAST:event_btnMostrarVentasActionPerformed

    private void btnMostrarPorProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarPorProveedorActionPerformed
        
        List<ResultadoSentencia> gastos=cbd.getGastosPorProveedor(cmbProveedoresz.getSelectedItem().toString().toUpperCase(),cmbTipo.getSelectedItem().toString(),this.getDesde(),this.getHasta());    
        String resultadoPantalla=this.formarTextoSalida(gastos);
        Double resultadoFormadoGastos=gastos.stream()
            .mapToDouble(e -> Double.valueOf(e.getCantidad()))
            .sum();
        txtAreaNombre.setText(resultadoPantalla+"\n\nTOTAL: "+resultadoFormadoGastos);

    }//GEN-LAST:event_btnMostrarPorProveedorActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnMostrarPorProveedorMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMostrarPorProveedorMouseEntered
        btnMostrarPorProveedor.setBackground((Color.BLUE));
    }//GEN-LAST:event_btnMostrarPorProveedorMouseEntered

    private void btnMostrarPorProveedorStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_btnMostrarPorProveedorStateChanged
    }//GEN-LAST:event_btnMostrarPorProveedorStateChanged

    private void btnDeudaProveedorMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDeudaProveedorMouseEntered
        btnDeudaProveedor.setBackground((Color.BLUE));
    }//GEN-LAST:event_btnDeudaProveedorMouseEntered

    private void btnDeudaProveedorMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDeudaProveedorMouseExited
        btnDeudaProveedor.setBackground((new Color(0,0,46))); 
    }//GEN-LAST:event_btnDeudaProveedorMouseExited

    private void btnBalanceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBalanceMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBalanceMouseClicked

    private void btnBalanceMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBalanceMouseEntered
         btnBalance.setBackground((Color.BLUE));

    }//GEN-LAST:event_btnBalanceMouseEntered

    private void btnBalanceMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBalanceMouseExited
         btnBalance.setBackground((new Color(0,0,46))); 

    }//GEN-LAST:event_btnBalanceMouseExited

    private void btnMostrarGastosRangoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMostrarGastosRangoMouseEntered
        btnMostrarGastosRango.setBackground((Color.BLUE));

    }//GEN-LAST:event_btnMostrarGastosRangoMouseEntered

    private void btnMostrarGastosRangoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMostrarGastosRangoMouseExited
        btnMostrarGastosRango.setBackground((new Color(0,0,46))); 

    }//GEN-LAST:event_btnMostrarGastosRangoMouseExited

    private void btnVentaDiaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVentaDiaMouseEntered
       btnVentaDia.setBackground((Color.BLUE));

    }//GEN-LAST:event_btnVentaDiaMouseEntered

    private void btnVentaDiaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVentaDiaMouseExited
        btnVentaDia.setBackground((new Color(0,0,46))); 

    }//GEN-LAST:event_btnVentaDiaMouseExited

    private void btnMostrarVentasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMostrarVentasMouseEntered
       btnMostrarVentas.setBackground((Color.BLUE));
    }//GEN-LAST:event_btnMostrarVentasMouseEntered

    private void btnMostrarVentasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMostrarVentasMouseExited
       btnMostrarVentas.setBackground((new Color(0,0,46))); 

    }//GEN-LAST:event_btnMostrarVentasMouseExited

    private void btnDetallesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDetallesMouseEntered
       btnDetalles.setBackground((Color.BLUE));
    }//GEN-LAST:event_btnDetallesMouseEntered

    private void btnDetallesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDetallesMouseExited
         btnDetalles.setBackground((new Color(0,0,46))); 

    }//GEN-LAST:event_btnDetallesMouseExited

    private void btnMostrarPorProveedorMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMostrarPorProveedorMouseExited
         btnMostrarPorProveedor.setBackground((new Color(0,0,46))); 

    }//GEN-LAST:event_btnMostrarPorProveedorMouseExited

    private void btnRecetasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRecetasActionPerformed
        new Recetario(this,true).setVisible(true);
    }//GEN-LAST:event_btnRecetasActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        new Graficas(this,true).setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAñadir;
    private javax.swing.JButton btnAñadirProveedor;
    private javax.swing.JButton btnBalance;
    private javax.swing.JButton btnBorrar;
    private javax.swing.JButton btnBorrarProveedor;
    private javax.swing.JButton btnDetalles;
    private javax.swing.JButton btnDeudaProveedor;
    private javax.swing.JButton btnMostrarGastosRango;
    private javax.swing.JButton btnMostrarPorProveedor;
    private javax.swing.JButton btnMostrarVentas;
    private javax.swing.JButton btnRecetas;
    private javax.swing.JButton btnRegistradora;
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton btnVentaDia;
    private javax.swing.JComboBox<String> cmbProveedoresz;
    private javax.swing.JComboBox<String> cmbTipo;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanelRegistrar;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblFondo;
    private javax.swing.JTextArea txtAreaNombre;
    private javax.swing.JTextField txtAñoDe;
    private javax.swing.JTextField txtAñoHa;
    private javax.swing.JTextField txtCantidad;
    private javax.swing.JTextField txtDiaDe;
    private javax.swing.JTextField txtDiaHa;
    private javax.swing.JTextField txtMesDe;
    private javax.swing.JTextField txtMesHa;
    private javax.swing.JTextField txtNombrePrveedor;
    // End of variables declaration//GEN-END:variables
}
