
import java.awt.Dimension;
import java.awt.Toolkit;
import java.util.List;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author petot
 */
public class Recetario extends javax.swing.JDialog {

    ConectorProfundo cP;
    public Recetario(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        cP=new ConectorProfundo();
      
    }
    public double getAncho(){
        Toolkit t = Toolkit.getDefaultToolkit();
        Dimension detectorDeDimensiones = Toolkit.getDefaultToolkit().getScreenSize();
        return detectorDeDimensiones.getWidth();

    }
      public double getAlto(){
        Toolkit t = Toolkit.getDefaultToolkit();
        Dimension detectorDeDimensiones = Toolkit.getDefaultToolkit().getScreenSize();
        return detectorDeDimensiones.getHeight();

    }
    public void recargarRecetas(){
        List<ResultadoSentencia> resultado=cP.lanzarSentenciaSelect("select tipo,tipo,tipo from tipoPlato;");

        resultado=cP.lanzarSentenciaSelect("select tipo,nombre,receta from recetas where tipo='"+cmbTipoReceta.getSelectedItem().toString()+"';");
        resultado.stream()
                .forEach(e -> cmbRecetas.addItem(e.getNombre()));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlFondo = new javax.swing.JPanel();
        pnlMostrarRecetas = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        cmbTipoReceta = new javax.swing.JComboBox<>();
        btnCargarRecetas = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        txtTipoReceta = new javax.swing.JTextField();
        btnAñadirTipoReceta = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtAreaIngredientees = new javax.swing.JTextArea();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAreaReceta = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        pnlAñadirReceta = new javax.swing.JPanel();
        btnAñadirReceta = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txtNombreReceta = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cmbRecetas = new javax.swing.JComboBox<>();
        btnVerReceta = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("RECETAS");
        setBackground(new java.awt.Color(255, 153, 51));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        pnlFondo.setBackground(new java.awt.Color(255, 153, 0));

        pnlMostrarRecetas.setBackground(new java.awt.Color(255, 204, 102));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("TIPO: ");

        cmbTipoReceta.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cmbTipoReceta.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbTipoRecetaItemStateChanged(evt);
            }
        });
        cmbTipoReceta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cmbTipoRecetaMouseClicked(evt);
            }
        });
        cmbTipoReceta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbTipoRecetaActionPerformed(evt);
            }
        });

        btnCargarRecetas.setBackground(new java.awt.Color(255, 153, 0));
        btnCargarRecetas.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnCargarRecetas.setForeground(new java.awt.Color(255, 255, 204));
        btnCargarRecetas.setText("CargarRecetas");
        btnCargarRecetas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCargarRecetasActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("AÑADIR TIPO RECETA");

        btnAñadirTipoReceta.setBackground(new java.awt.Color(255, 153, 0));
        btnAñadirTipoReceta.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnAñadirTipoReceta.setForeground(new java.awt.Color(255, 255, 204));
        btnAñadirTipoReceta.setText("AÑADIR");
        btnAñadirTipoReceta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAñadirTipoRecetaActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("TIPO: ");

        javax.swing.GroupLayout pnlMostrarRecetasLayout = new javax.swing.GroupLayout(pnlMostrarRecetas);
        pnlMostrarRecetas.setLayout(pnlMostrarRecetasLayout);
        pnlMostrarRecetasLayout.setHorizontalGroup(
            pnlMostrarRecetasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMostrarRecetasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlMostrarRecetasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlMostrarRecetasLayout.createSequentialGroup()
                        .addGroup(pnlMostrarRecetasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(pnlMostrarRecetasLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(pnlMostrarRecetasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnCargarRecetas, javax.swing.GroupLayout.DEFAULT_SIZE, 239, Short.MAX_VALUE)
                                    .addComponent(cmbTipoReceta, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(pnlMostrarRecetasLayout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                                .addGroup(pnlMostrarRecetasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnAñadirTipoReceta, javax.swing.GroupLayout.DEFAULT_SIZE, 236, Short.MAX_VALUE)
                                    .addComponent(txtTipoReceta)
                                    .addGroup(pnlMostrarRecetasLayout.createSequentialGroup()
                                        .addGap(12, 12, 12)
                                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(23, 23, 23))
                    .addGroup(pnlMostrarRecetasLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        pnlMostrarRecetasLayout.setVerticalGroup(
            pnlMostrarRecetasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMostrarRecetasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlMostrarRecetasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbTipoReceta, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addComponent(btnCargarRecetas, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlMostrarRecetasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtTipoReceta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(btnAñadirTipoReceta)
                .addContainerGap())
        );

        txtAreaIngredientees.setColumns(20);
        txtAreaIngredientees.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        txtAreaIngredientees.setRows(5);
        jScrollPane2.setViewportView(txtAreaIngredientees);

        txtAreaReceta.setColumns(20);
        txtAreaReceta.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        txtAreaReceta.setRows(5);
        jScrollPane1.setViewportView(txtAreaReceta);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 204));
        jLabel5.setText("INGREDIENTES");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 204));
        jLabel1.setText("RECETA");

        pnlAñadirReceta.setBackground(new java.awt.Color(255, 204, 102));

        btnAñadirReceta.setBackground(new java.awt.Color(255, 153, 0));
        btnAñadirReceta.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnAñadirReceta.setForeground(new java.awt.Color(255, 255, 204));
        btnAñadirReceta.setText("AÑADIR");
        btnAñadirReceta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAñadirRecetaActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("AÑADIR UNA RECETA NUEVA");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("NOMBRE:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("RECETAS: ");

        cmbRecetas.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cmbRecetas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbRecetasActionPerformed(evt);
            }
        });

        btnVerReceta.setBackground(new java.awt.Color(255, 153, 0));
        btnVerReceta.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnVerReceta.setForeground(new java.awt.Color(255, 255, 204));
        btnVerReceta.setText("VER");
        btnVerReceta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerRecetaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlAñadirRecetaLayout = new javax.swing.GroupLayout(pnlAñadirReceta);
        pnlAñadirReceta.setLayout(pnlAñadirRecetaLayout);
        pnlAñadirRecetaLayout.setHorizontalGroup(
            pnlAñadirRecetaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlAñadirRecetaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlAñadirRecetaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addGroup(pnlAñadirRecetaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlAñadirRecetaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlAñadirRecetaLayout.createSequentialGroup()
                            .addGroup(pnlAñadirRecetaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(btnAñadirReceta, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 239, Short.MAX_VALUE)
                                .addComponent(txtNombreReceta, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addGap(21, 21, 21))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlAñadirRecetaLayout.createSequentialGroup()
                            .addComponent(jLabel4)
                            .addGap(44, 44, 44)))
                    .addGroup(pnlAñadirRecetaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(cmbRecetas, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnVerReceta, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 235, Short.MAX_VALUE))))
        );
        pnlAñadirRecetaLayout.setVerticalGroup(
            pnlAñadirRecetaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlAñadirRecetaLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(pnlAñadirRecetaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbRecetas, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnVerReceta, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pnlAñadirRecetaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNombreReceta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addComponent(btnAñadirReceta)
                .addContainerGap())
        );

        javax.swing.GroupLayout pnlFondoLayout = new javax.swing.GroupLayout(pnlFondo);
        pnlFondo.setLayout(pnlFondoLayout);
        pnlFondoLayout.setHorizontalGroup(
            pnlFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFondoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlMostrarRecetas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnlAñadirReceta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(pnlFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlFondoLayout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 541, Short.MAX_VALUE))
                    .addGroup(pnlFondoLayout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnlFondoLayout.setVerticalGroup(
            pnlFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFondoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlFondoLayout.createSequentialGroup()
                        .addGroup(pnlFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnlFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 467, Short.MAX_VALUE)
                            .addComponent(jScrollPane2))
                        .addContainerGap(68, Short.MAX_VALUE))
                    .addGroup(pnlFondoLayout.createSequentialGroup()
                        .addComponent(pnlMostrarRecetas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(pnlAñadirReceta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlFondo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
          this.cargarTipoPlatos();
       
    }//GEN-LAST:event_formWindowOpened
    public void  cargarTipoPlatos(){
        List<ResultadoSentencia> resultado=cP.lanzarSentenciaSelect("select tipo,tipo,tipo from tipoPlato;");
        resultado.stream()
                .forEach(e -> cmbTipoReceta.addItem(e.getNombre()));
    }
    private void btnAñadirRecetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAñadirRecetaActionPerformed
        String ingredientes=txtAreaIngredientees.getText();
        String receta=txtAreaReceta.getText();
        String tipo=cmbTipoReceta.getSelectedItem().toString();
        String nombre=txtNombreReceta.getText();
        int todoOk=cP.lanzarSentencia("insert into recetas values ('"+tipo+"','"+nombre+"','"+receta+"','"+ingredientes+"');");
        
        if(todoOk==1){
            JOptionPane.showMessageDialog(rootPane,"Receta guardada");
            this.setVisible(false);
            new Recetario(new Principal(),false).setVisible(true);
        }else{
            JOptionPane.showMessageDialog(rootPane,"Revisa los datos");
        }
        
    }//GEN-LAST:event_btnAñadirRecetaActionPerformed

    private void cmbRecetasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbRecetasActionPerformed
    }//GEN-LAST:event_cmbRecetasActionPerformed

    private void cmbTipoRecetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbTipoRecetaActionPerformed
       
    }//GEN-LAST:event_cmbTipoRecetaActionPerformed

    private void cmbTipoRecetaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmbTipoRecetaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbTipoRecetaMouseClicked

    private void btnVerRecetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerRecetaActionPerformed
        List<ResultadoSentencia> resultado=cP.lanzarSentenciaSelect(
                "select ingredientes,receta,nombre from recetas where nombre='"+
                        cmbRecetas.getSelectedItem().toString()+"' and tipo ='"+
                        cmbTipoReceta.getSelectedItem().toString()+"';");
        txtAreaIngredientees.setText(resultado.get(0).getCantidad());//donde cantidad es el dato 1 por lo tanto los ingredientes
        txtAreaReceta.setText("       RECETA DE: "+cmbRecetas.getSelectedItem().toString()+"\n\n"+resultado.get(0).getNombre());
    }//GEN-LAST:event_btnVerRecetaActionPerformed

    private void cmbTipoRecetaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbTipoRecetaItemStateChanged
    
    }//GEN-LAST:event_cmbTipoRecetaItemStateChanged

    private void btnCargarRecetasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCargarRecetasActionPerformed
        List<ResultadoSentencia> resultado=cP.lanzarSentenciaSelect(
                "select ingredientes,nombre,receta from recetas where tipo ='"+
                        cmbTipoReceta.getSelectedItem().toString()+"';");
        cmbRecetas.removeAllItems();
        resultado.stream()
                .forEach(e -> cmbRecetas.addItem(e.getNombre()));
       
    }//GEN-LAST:event_btnCargarRecetasActionPerformed

    private void btnAñadirTipoRecetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAñadirTipoRecetaActionPerformed
        if(!txtTipoReceta.getText().equals("")||!txtTipoReceta.getText().equals(" ")){
            cP.lanzarSentencia("Insert into tipoplato values ('"+txtTipoReceta.getText()+"');");
            cmbTipoReceta.removeAllItems();
            this.cargarTipoPlatos();
        }else{
            JOptionPane.showMessageDialog(rootPane, "rellena el tipod de plato");
        }
    }//GEN-LAST:event_btnAñadirTipoRecetaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Recetario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Recetario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Recetario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Recetario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Recetario dialog = new Recetario(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAñadirReceta;
    private javax.swing.JButton btnAñadirTipoReceta;
    private javax.swing.JButton btnCargarRecetas;
    private javax.swing.JButton btnVerReceta;
    private javax.swing.JComboBox<String> cmbRecetas;
    private javax.swing.JComboBox<String> cmbTipoReceta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel pnlAñadirReceta;
    private javax.swing.JPanel pnlFondo;
    private javax.swing.JPanel pnlMostrarRecetas;
    private javax.swing.JTextArea txtAreaIngredientees;
    private javax.swing.JTextArea txtAreaReceta;
    private javax.swing.JTextField txtNombreReceta;
    private javax.swing.JTextField txtTipoReceta;
    // End of variables declaration//GEN-END:variables
}
